# Imagen base MySQL 8 oficial
FROM mysql:8

# Copiar el script de inicializacion dentro de la imagen.
# Se ejecuta automaticamente la primera vez que se levante el contenedor.
COPY init.sql /docker-entrypoint-initdb.d/

# Exponer el puerto de MySQL
EXPOSE 3306
